version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_DB_URI: mongodb://mongo:27017/nestjs-db
