version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - my-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: offer-zone-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: offer-zone-app
    networks:
      - my-network
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_URI: mongodb://root:rootpassword@mongo:27017/offer-zone-db?authSource=admin
      JWT_SECRET: d3b07384d113edec49eaa6238ad5ff00
      JWT_EXPIRES_IN: 15m
    depends_on:
      - mongo

networks:
  my-network:
    driver: bridge