apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: dockerartisan/offer-zone-devops:latest
        ports:
        - containerPort: 3000
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
