apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer-zone-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-zone-devops
  template:
    metadata:
      labels:
        app: offer-zone-devops
    spec:
      containers:
      - name: offer-zone-devops
        image: dockerartisan/offer-zone-devops:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/offer-zone-devops-db
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: offer-zone-devops
