apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: offer-zone
        image: dockerartisan/offer-zone-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_DB_URI
          value: mongodb://mongo-service:27017/offer-zone-db
